/**
 * MusicPlayer implementation skeleton.
 * Replace TODOs with actual ESP-IDF / ESP-ADF calls in your environment.
 */
#include "MusicPlayer.h"
#include <string.h>

#include <string.h>
#include <sys/unistd.h>
#include <driver/i2s_std.h>
#include <driver/i2c_master.h>
#include "driver/gpio.h"
#include "esp_log.h"
#include "mp3dec.h"
#include "audio_player.h"
#include "audio_mp3.h"
//#include "esp_timer.h"

#include "esp_system.h"
#include <stdio.h>

static const char *TAG3 = "MusicPlayer";
#define BUFFER_SIZE 2048
#define USING_CUSTOM_BOARD
uint32_t prevFreq = 44100;

WM8731RegisterCustom myWM8731 = {};

MusicPlayer::MusicPlayer() : 
    current_track(),
    volume(0.4f),
    is_playing(false),
    play_mode(0),
    tx_handle(NULL) {

    }

/* Start playing a specific track. */
esp_err_t MusicPlayer::music_player_play(struct MusicPlayer *mp, const char *track_path) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Pause playback. */
esp_err_t MusicPlayer::music_player_pause(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Stop playback. */
esp_err_t MusicPlayer::music_player_stop(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Resume playback. */
esp_err_t MusicPlayer::music_player_resume(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Skip to next track. */
esp_err_t MusicPlayer::music_player_next_track(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Go back to previous track. */
esp_err_t MusicPlayer::music_player_previous_track(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Set volume level. */
void MusicPlayer::music_player_set_volume(struct MusicPlayer *mp, int level) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Enable shuffle mode. */
void MusicPlayer::music_player_shuffle(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Enable repeat mode. */
void MusicPlayer::music_player_repeat(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Write human-readable status into out_buf. */
void MusicPlayer::music_player_get_status(struct MusicPlayer *mp, char *out_buf, int out_len) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}



/**
 * @brief A Test Function. Initializes an I2S bus and handle.
 */
void MusicPlayer::testInitI2S() {
    // Create i2s channel, init channel, enable, read/write
    // Most backend data transfer is done via DMA. There is a DMA
    // buffer and a source/destination buffer
    // Writing uses i2s_channel_write() which copies from a source buffer
    // into DMA, and I2S hardware will access DMA
    // Function will wait until all of source buffer is sent, or timeout

    
    /* Get the default channel configuration by the helper macro.
    * This helper macro is defined in `i2s_common.h` and shared by all the I2S communication modes.
    * It can help to specify the I2S role and port ID */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    /* Allocate a new TX channel and get the handle of this channel */
    i2s_new_channel(&chan_cfg, &tx_handle, NULL);

    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
#ifdef USING_CUSTOM_BOARD    
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(prevFreq),
        // MCLK 12.288MHz for 48kHz, 11.2896MHz for 44.1kHz
        // It's Going Down Now uses 48khz, Breath of the Wild Main Theme uses 44.1khz
        // THe freq and bit width should be encoded in the mp3 metadata 
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),

        // NOTE, the I2S mode on the WM8731 is probably philips mode
        //.slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = GPIO_NUM_5, // How can you confirm that the master clock is outputting?
            .bclk = GPIO_NUM_15,
            .ws = GPIO_NUM_17,
            .dout = GPIO_NUM_16,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = true,
                .bclk_inv = false,
                .ws_inv = true,
            },
        },
    };
#else
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(prevFreq),
        // It's Going Down Now uses 48khz, Breath of the Wild Main Theme uses 44.1khz
        // THe freq and bit width should be encoded in the mp3 metadata 
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = GPIO_NUM_13,
            .ws = GPIO_NUM_14,
            .dout = GPIO_NUM_12,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
#endif



    /* Initialize the channel */
    i2s_channel_init_std_mode(tx_handle, &std_cfg);

    /* Before writing data, start the TX channel first */
   
}

/**
 * @brief A Test Function. Send an abs path to a WAV file to play it via I2S.
 * @param file a c-style string being the absolute path to a wav file
 */
void MusicPlayer::testWavAudioI2S(const char *file) {

    FILE *f = fopen(file, "rb"); // Treat WAV file as is, no character conversion
    if (f == nullptr) {
        ESP_LOGE(TAG3, "Failed to open file: %s", file);
        return;
    }
    ESP_LOGI(TAG3, "Starting WAV playback on %s", file);
    // Allocating heap memory for buffer (alternatively call calloc)
    // NOTE: reading as uint is different from reading int!
    // Sounds fluctuates between + and - of the refernce point - always using unsigned means
    // all digital sound is converted positive, thus an explanation for why there is a lot of
    // unintelligible noises. Even so, it doesn't remove the clipping on its own.
    // Based off of what is printed in firmware, it's most likely that clipping is caused because
    // the power rails for the amp can't supply enough current, so it peaks
    // Also, what difference is there reading the file as int16 or an int8?
    int8_t *src_buf = (int8_t*) malloc(BUFFER_SIZE*sizeof(int8_t));
    memset(src_buf, 0, BUFFER_SIZE);

    i2s_channel_enable(tx_handle);

    size_t bytes_written = 0;
    size_t elements = fread(src_buf, sizeof(int8_t), BUFFER_SIZE, f);

    size_t count = 0;
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiON, 2, 100);
    while(elements > 0 && count < 2000) { //
        if (count % 200 == 0) {
            ESP_LOGI(TAG3, "%d %d %d %d %d %d %d %d %d %d ", 
                src_buf[0], 
                src_buf[1], 
                src_buf[2],
                src_buf[3],
                src_buf[4],
                src_buf[5],
                src_buf[6],
                src_buf[7],
                src_buf[8],
                src_buf[9]
            );
            
            //printf("\n");
        } 

        for (int i = 0; i < BUFFER_SIZE; i++) {
            src_buf[i] = (int8_t)(src_buf[i] * volume);

            // // Hard clamp to prevent overflow
            // if (temp > 32767) temp = 32767;
            // if (temp < -32768) temp = -32768;
        }

        // Why must the third parameter be buffer_size * sizeof(int16_t)
        // Because the third parameter wants to know how many total BYTES your buffer has
        // That would be your BUFFER_SIZE (aka the number of elements) * sizeof(int16_t) (data type per element)
        i2s_channel_write(tx_handle, src_buf, BUFFER_SIZE*sizeof(int8_t), &bytes_written, 100);
        elements = fread(src_buf, sizeof(int8_t), BUFFER_SIZE, f);
        if (bytes_written != BUFFER_SIZE*sizeof(int8_t)) {
            ESP_LOGW(TAG3, "Only %d/%d bytes written", bytes_written, BUFFER_SIZE);
        }
        count++;
    }
    
    /* If the configurations of slot or clock need to be updated, stop the channel first and then update it */
    // i2s_channel_disable(tx_handle);
    // std_cfg.slot_cfg.slot_mode = I2S_SLOT_MODE_MONO; // Default is stereo
    // i2s_channel_reconfig_std_slot(tx_handle, &std_cfg.slot_cfg);
    // std_cfg.clk_cfg.sample_rate_hz = 96000;
    // i2s_channel_reconfig_std_clock(tx_handle, &std_cfg.clk_cfg);

    printf("Song End\n");

    i2s_channel_disable(tx_handle);
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiOFF, 2, 100);
    
    /* Clean up resources */
    if (src_buf != nullptr) {
        free(src_buf);
    }
    if (f != nullptr) {
        fclose(f);
    }
}

/**
 * TODO: FIGURE OUT WHY i2c is BLOCKING FOR SO LONG!
 */
bool MusicPlayer::testReconfigI2S(uint32_t freq, int bitsPerSample, int channels) {
    i2s_channel_disable(tx_handle);
    
    if (freq == 0 || bitsPerSample == 0 || channels == 0) {
        
        ESP_LOGE(TAG3, "A ZERO VALUE DETECTED");
        return false;
    }
    i2s_std_clk_config_t config = I2S_STD_CLK_DEFAULT_CONFIG(freq);
    i2s_channel_reconfig_std_clock(tx_handle, &config);
    ESP_LOGI(TAG3, "Probing WM8731");
    ESP_LOGI(TAG3, "Probe Results: %d", i2c_master_probe(bus_handle, (uint16_t) wm8731Addr, 100));
    ESP_LOGI(TAG3, "Deactivating DAI");
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiOFF, 2, 100);
    if (freq == 44100) {
        ESP_LOGI(TAG3, "Sample Rate is 44100");
        i2c_master_transmit(dev_handle, myWM8731.addr_8E_44k1, 2, 100);
        ESP_LOGI(TAG3, "I2C written");
    } else if (freq == 48000) {
        ESP_LOGI(TAG3, "Sample Rate is 48000");
        i2c_master_transmit(dev_handle, myWM8731.addr_8E_48k, 2, 100);
        ESP_LOGI(TAG3, "I2C written");
    }
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiON, 2, 100);
    //i2c_master_transmit(dev_handle, myWM8731.addr_8E_48k, 2, 100);
    ESP_LOGI(TAG3, "Channel Reconfig'ed");
    return true;

}

void MusicPlayer::testMP3AudioI2S(const char *file) {
    
    /* 
    I originally wanted to use minimp3 for decoding but here's a blog about someone testing it on STM32
    http://cmorgan.org/2023/10/05/mp3-decoding-on-embedded.html
    Performance on STM32 was limited, and despite ESP32S3 having dual core, there's a chance that minimp3
    won't get the results we're looking for, and such process to debug and optimize will take too much time
    Additionally, minimp3 supports NEON and SSE architectures extensions for ARM and x86 respectively
    ESP is Xtensa, so this support is limited.
    We'll need to search for another alternative. Checking out Helix MP3 for esp32
    https://github.com/chmorgan/esp-libhelix-mp3?tab=readme-ov-file
    Here's a forum related to our issue https://esp32.com/viewtopic.php?t=40413 
    Alternatively there's also the audio development framework

    esp-libhelix-mp3 is an extended version of libhelix-mp3 by chmorgan. The main code files in this
    librariy are mp3dec.h and mp3common.h, where the first is a high level code, and the latter low level
    chmorgan also made a library/project called audioPlayer where his high level code uses mp3dec.h, which
    is libhelix-mp. You can find that example here:  
    https://github.com/chmorgan/esp-audio-player/blob/main/test/audio_player_test.c
    
    To install esp-libhelix-mp3 or libhelix-mp3 libraries, you need to git clone the repo into the
    components folder and activate it as a component use CMakeLists.txt

    To use the higher level audioPLayer library that chmorgan made (audio_player.h), you need to open an
    ESP-IDF terminal and install using the command "idf.py add-dependency chmorgan/esp-audio-player"

    Upon building you can then use audio_player.h or audio_mp3.h, the latter being a wrapper for mp3dec.h

    The advanced development framework also has support for mp3 decoding found here:
    https://docs.espressif.com/projects/esp-adf/en/latest/api-reference/codecs/mp3_decoder.html
    But ADF is advanced high level abstract code - it does a lot of processes automatically, and wraps everything up using pipelines
    For our project, GPT considers it overkill to use ADF. Plus, ADF is harder to set up and uses a lot of memory
    It also leads me away from the low level learning I want. 

    Also, esp-libhelix-mp3 uses a branch of libhelix-mp3 that is 8 years old. Maybe consider just using libhelix-mp3 alone
    */

    FILE *f = fopen(file, "rb");
    if (f == nullptr) {
        ESP_LOGW(TAG3, "Failed to open file: %s", file);
        return;
    }

    // is_mp3() seems to be inconsistent. Sometimes it will think a mp3 file is not an mp3, and sometimes it skips wav files?
    // Requires further testing to see under what conditions the function fails
    if (!is_mp3(f)) {
        ESP_LOGW(TAG3, "The following file is not a MP3: %s", file);
        fclose(f);
        return;
    }
    //ESP_LOGI(TAG3, "Starting decoding process");
    ESP_LOGI(TAG3, "Starting MP3 playback on %s", file);

    
    HMP3Decoder myDecoder = MP3InitDecoder();
    // Notice that the structs use uint8 buffers. These buffers are to be treated as raw byte arrays instead of
    // pure audio samples, which should come in signed form. THe output seems to be uint8 as well, but some how
    // we need to make sure the output to I2S is signed
    decode_data output;
    output.samples_capacity = 2 * 2 * 576; // 2 * 2 * 576 as set by example
    output.samples_capacity_max = output.samples_capacity*2; ///size_t
    output.samples = static_cast<uint8_t*>(malloc(output.samples_capacity_max)); //uint8_t*
    memset(output.samples, 0, output.samples_capacity_max);
    // THe rest is set by the function decodeMP3
    output.frame_count = 0; //size_t ??
    output.fmt = {
        .sample_rate = 0, //int ??
        .bits_per_sample = 0, //uint32_t ??
        .channels = 2 //uint32_t
    };
    
    mp3_instance mp3_data;
    mp3_data.data_buf_size = 1940 * 3; // 1940 * 3 previously set by example
    mp3_data.data_buf = static_cast<uint8_t*>(malloc(mp3_data.data_buf_size)); //uint8_t*
    memset(mp3_data.data_buf, 0, mp3_data.data_buf_size);
    mp3_data.bytes_in_data_buf = 0; //size_t
    mp3_data.read_ptr = mp3_data.data_buf; //uint8_t*
    mp3_data.eof_reached = false;

    DECODE_STATUS status = DECODE_STATUS_ERROR;
    size_t bytesWritten = 0;
    // size_t averageDigitalAudio = 0;

    i2s_channel_enable(tx_handle);
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiON, 2, 100);

    int count = 0;
    
    while (true && count < 1500) { //
        // ESP_LOGI(TAG3, "NEW LOOP", status);
        // long time = esp_timer_get_time();
        status = decode_mp3(myDecoder, f, &output, &mp3_data);
        if (status == DECODE_STATUS_NO_DATA_CONTINUE) {
            ESP_LOGW(TAG3, "Something went wrong...");
            break;
        }
        // printf("----TOTAL DECODE TIME: %lld ms\n", esp_timer_get_time() - time);
        // time = esp_timer_get_time();
        size_t bytesToWrite = output.frame_count * output.fmt.channels * (output.fmt.bits_per_sample / 8);

        // Reduce audio volume
        for (int i = 0; i < output.samples_capacity_max; i++) {
            output.samples[i] = ((uint8_t) ((int8_t)(output.samples[i])*volume));
            //averageDigitalAudio += (int8_t) (output.samples[i]);
        }
        //printf("Avg Audio: %f, Avg Capacity: %d\n", averageDigitalAudio/((float)(output.samples_capacity_max)), output.samples_capacity_max);
        //averageDigitalAudio = 0;

        
        // if (count % 100 == 0) {
        //     ESP_LOGI(TAG3, "%d %d %d %d %d %d %d %d %d %d ", 
        //         output.samples[0], 
        //         output.samples[1], 
        //         output.samples[2],
        //         output.samples[3],
        //         output.samples[4],
        //         output.samples[5],
        //         output.samples[6],
        //         output.samples[7],
        //         output.samples[8],
        //         output.samples[9]
        //     );
        // } 
        
        // Print mp3 frame properties
        if (count == 0) {
            ESP_LOGI(TAG3, "Freq: %d Hz, Channels: %d, Bit/Sample: %d", output.fmt.sample_rate, output.fmt.channels, output.fmt.bits_per_sample);
            count++;
        }

        // Check if mp3 sample_rate matches I2S
        if (output.fmt.sample_rate != prevFreq) {

            prevFreq = output.fmt.sample_rate;
            ESP_LOGI(TAG3, "Entered if statement");
            if(!testReconfigI2S(output.fmt.sample_rate, output.fmt.bits_per_sample, output.fmt.channels)) {
                printf("Problem with file %s\n", file);
                break;
             }
            i2s_channel_enable(tx_handle);
        }
        
        // printf("----TOTAL PRE-I2S CHECK TIME: %lld ms\n", esp_timer_get_time() - time);
        // time = esp_timer_get_time();

        i2s_channel_write(tx_handle, (int8_t*) (output.samples), bytesToWrite*sizeof(int8_t), &bytesWritten, 100);

        // printf("----TOTAL I2S WRITE TIME: %lld ms\n", esp_timer_get_time() - time);
        // time = esp_timer_get_time();
        

        if (bytesToWrite != bytesWritten) {
            ESP_LOGW(TAG3, "Bytes written: %d/%d", bytesWritten, bytesToWrite);
        }
        
        if (status != DECODE_STATUS_CONTINUE && status != DECODE_STATUS_NO_DATA_CONTINUE) {
            ESP_LOGI(TAG3, "End of song reached");
            break;
        }
        count++;
    }

    

    free(output.samples);
    free(mp3_data.data_buf);
    MP3FreeDecoder(myDecoder);

    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiOFF, 2, 100);
    i2s_channel_disable(tx_handle);
    fclose(f);
}

void MusicPlayer::testCloseI2S() {
    //i2s_channel_disable(tx_handle);
    i2s_del_channel(tx_handle);
    
}

void MusicPlayer::testRunI2C() {

    i2c_master_bus_config_t i2c_mst_config = {
        .i2c_port = 0,
        .sda_io_num = GPIO_NUM_7,
        .scl_io_num = GPIO_NUM_6,
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .glitch_ignore_cnt = 7
    };

    //i2c_master_bus_handle_t bus_handle;
    ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_mst_config, &bus_handle));

    i2c_device_config_t dev_cfg = {
        .dev_addr_length = I2C_ADDR_BIT_LEN_7,
        .device_address = wm8731Addr,
        .scl_speed_hz = 100000,
    };

    // i2c_master_dev_handle_t dev_handle;
    ESP_ERROR_CHECK(i2c_master_bus_add_device(bus_handle, &dev_cfg, &dev_handle));

    // Test send
    uint8_t data[2] = {0, 0};
    i2c_master_transmit(dev_handle, data, 2, 100);

    // Reset
    i2c_master_transmit(dev_handle, myWM8731.addr_FE, 2, 100);

    // Power Down
    i2c_master_transmit(dev_handle, myWM8731.addr_6E, 2, 100);

    i2c_master_transmit(dev_handle, myWM8731.addr_0E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_1E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_2E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_3E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_4E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_5E_44k1, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_7E, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_8E_44k1, 2, 100);
    i2c_master_transmit(dev_handle, myWM8731.addr_9E_daiOFF, 2, 100);

    //i2c_master_transmit(dev_handle, myWM8731.addr_0E, 4, 100);
    ESP_LOGI(TAG3, "Probe Results: %d", i2c_master_probe(bus_handle, (uint16_t) wm8731Addr, 100));

}

void MusicPlayer::testCloseI2C() {
    uint8_t d[2] = {0x06 << 1, 0b01100111};
    uint8_t d2[2] = {0x03 << 1, 0b00000000};                    
    i2c_master_transmit(dev_handle, d, 2, 100);
    //i2c_master_transmit(dev_handle, d2, 2, 100);
}