/**
 * MusicPlayer implementation skeleton.
 * Replace TODOs with actual ESP-IDF / ESP-ADF calls in your environment.
 */
#include "MusicPlayer.h"
#include <string.h>

#include <string.h>
#include <sys/unistd.h>
#include <driver/i2s_std.h>
#include "driver/gpio.h"
#include "esp_log.h"

static const char *TAG3 = "MusicPlayer";
#define BUFFER_SIZE 2048

i2s_chan_handle_t tx_handle;

/* Start playing a specific track. */
esp_err_t MusicPlayer::music_player_play(struct MusicPlayer *mp, const char *track_path) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Pause playback. */
esp_err_t MusicPlayer::music_player_pause(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Stop playback. */
esp_err_t MusicPlayer::music_player_stop(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Resume playback. */
esp_err_t MusicPlayer::music_player_resume(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Skip to next track. */
esp_err_t MusicPlayer::music_player_next_track(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Go back to previous track. */
esp_err_t MusicPlayer::music_player_previous_track(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
    return ESP_OK;
}

/* Set volume level. */
void MusicPlayer::music_player_set_volume(struct MusicPlayer *mp, int level) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Enable shuffle mode. */
void MusicPlayer::music_player_shuffle(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Enable repeat mode. */
void MusicPlayer::music_player_repeat(struct MusicPlayer *mp) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}

/* Write human-readable status into out_buf. */
void MusicPlayer::music_player_get_status(struct MusicPlayer *mp, char *out_buf, int out_len) {
    /* TODO: Implement using ESP-IDF/ADF APIs */
}



/**
 * @brief A Test Function. Initializes an I2S bus and handle.
 */
void MusicPlayer::testInitI2S() {
    // Create i2s channel, init channel, enable, read/write
    // Most backend data transfer is done via DMA. There is a DMA
    // buffer and a source/destination buffer
    // Writing uses i2s_channel_write() which copies from a source buffer
    // into DMA, and I2S hardware will access DMA
    // Function will wait until all of source buffer is sent, or timeout

    
    /* Get the default channel configuration by the helper macro.
    * This helper macro is defined in `i2s_common.h` and shared by all the I2S communication modes.
    * It can help to specify the I2S role and port ID */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    /* Allocate a new TX channel and get the handle of this channel */
    i2s_new_channel(&chan_cfg, &tx_handle, NULL);

    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros are defined in `i2s_std.h` which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        // It's Going Down Now uses 48khz, Breath of the Wild Main Theme uses 44.1khz
        // THe freq and bit width should be encoded in the mp3 metadata 
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = GPIO_NUM_13,
            .ws = GPIO_NUM_14,
            .dout = GPIO_NUM_12,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    /* Initialize the channel */
    i2s_channel_init_std_mode(tx_handle, &std_cfg);

    /* Before writing data, start the TX channel first */
   
}

/**
 * @brief A Test Function. Send an abs path to a WAV file to play it via I2S.
 * @param file a c-style string being the absolute path to a wav file
 */
void MusicPlayer::testWavAudioI2s(const char *file) {
    FILE *f = fopen(file, "rb"); // Treat WAV file as is, no character conversion
    if (f == nullptr) {
        ESP_LOGE(TAG3, "Failed to open file: %s", file);
        return;
    }
    
    // Allocating heap memory for buffer (alternatively call calloc)
    // NOTE: reading as uint is different from reading int!
    // Sounds fluctuates between + and - of the refernce point - always using unsigned means
    // all digital sound is converted positive, thus an explanation for why there is a lot of
    // unintelligible noises. Even so, it doesn't remove the clipping on its own.
    // Based off of what is printed in firmware, it's most likely that clipping is caused because
    // the power rails for the amp can't supply enough current, so it peaks
    // Also, what difference is there reading the file as int16 or an int8?
    int16_t *src_buf = (int16_t*) malloc(BUFFER_SIZE*sizeof(int16_t));
    memset(src_buf, 0, BUFFER_SIZE);

    i2s_channel_enable(tx_handle);

    size_t bytes_written = 0;
    size_t elements = fread(src_buf, sizeof(int16_t), BUFFER_SIZE, f);

    float volume = 0.25f;   // 25% volume (0.0 → silent, 1.0 → full scale
    while(elements > 0) {
        // for (int i = 0; i < 20; i++) {
        //     printf("%d ", src_buf[i]);
        // }
        // printf("\n");

        for (int i = 0; i < BUFFER_SIZE; i++) {
            src_buf[i] = (int16_t)(src_buf[i] * volume);

            // // Hard clamp to prevent overflow
            // if (temp > 32767) temp = 32767;
            // if (temp < -32768) temp = -32768;
        }

        // Why must the third parameter be buffer_size * sizeof(int16_t)
        // Because the third parameter wants to know how many total BYTES your buffer has
        // That would be your BUFFER_SIZE (aka the number of elements) * sizeof(int16_t) (data type per element)
        i2s_channel_write(tx_handle, src_buf, BUFFER_SIZE*sizeof(int16_t), &bytes_written, 100);
        elements = fread(src_buf, sizeof(int16_t), BUFFER_SIZE, f);
        if (bytes_written != BUFFER_SIZE*sizeof(int16_t)) {
            ESP_LOGW(TAG3, "Only %d/%d bytes written", bytes_written, BUFFER_SIZE);
        }
    }
    
    /* If the configurations of slot or clock need to be updated, stop the channel first and then update it */
    // i2s_channel_disable(tx_handle);
    // std_cfg.slot_cfg.slot_mode = I2S_SLOT_MODE_MONO; // Default is stereo
    // i2s_channel_reconfig_std_slot(tx_handle, &std_cfg.slot_cfg);
    // std_cfg.clk_cfg.sample_rate_hz = 96000;
    // i2s_channel_reconfig_std_clock(tx_handle, &std_cfg.clk_cfg);

    printf("Song End\n");

    i2s_channel_disable(tx_handle);
    
    /* Clean up resources */
    if (src_buf != nullptr) {
        free(src_buf);
    }
    if (f != nullptr) {
        fclose(f);
    }
}

void MusicPlayer::testCloseI2S() {
    i2s_del_channel(tx_handle);
}